steps:
  - name: "gcr.io/cloud-builders/docker"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        docker pull gcr.io/$PROJECT_ID/gcp-app || exit 0

  # Build the application image
  - name: "gcr.io/cloud-builders/docker"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        docker build \
        --cache-from gcr.io/$PROJECT_ID/gcp-app \
        -t gcr.io/$PROJECT_ID/gcp-app \
        . && docker push gcr.io/$PROJECT_ID/gcp-app

  # Deploy to cloud run
  - name: "gcr.io/cloud-builders/gcloud"
    args: [
        "run",
        "deploy",
        "$PROJECT_ID", # We are naming the cloudrun service the same as our project id
        "--image",
        "gcr.io/$PROJECT_ID/gcp-app",
        "--no-traffic", # deployment step
        "--region",
        "australia-southeast1",
        "--platform",
        "managed",
      ]

  # Switch 50% of all traffic over to the latest version.
  - name: "gcr.io/cloud-builders/gcloud"
    args: [
        "run",
        "services",
        "update-traffic",
        "$PROJECT_ID", # We are naming the cloudrun service the same as our project id
        # "--to-latest",
        "--to-revisions=LATEST=50",
        "--region",
        "australia-southeast1",
        "--platform",
        "managed",
      ]

timeout: 800s
